version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22  # Updated to Node.js version 22
    commands:
      - echo Installing dependencies...
      - npm --version  # Debugging: Ensure it shows npm 10.8.1
      - node --version  # Debugging: Ensure it shows Node.js 22.4
      - npm install
  pre_build:
    commands:
      - echo Running pre-build tasks...
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'

cache:
  paths:
    - 'node_modules/**/*'
